version: 0.2

phases:
  install:
    runtime-versions:
      php: 5.6.3
    commands:
      - composer install # or any other dependency manager
  pre_build:
    commands:
      # Set MySQL username, password, and database name
      - MYSQL_USER="admin"
      - MYSQL_PASSWORD="admin"
      - DATABASE_NAME="inventory_system"
      - wget https://github.com/Ganesh-DevOps-Eng/InventorySystem_PHP.git
      - unzip InventorySystem_PHP.zip -d /var/www/html/
      - cd /var/www/html/DATABASE FILE/
      - MYSQL_HOST=$(/usr/bin/aws rds describe-db-instances --db-instance-identifier ${var.project_name}-rds --query 'DBInstances[0].Endpoint.Address' --output text)
      - mysql -h "$MYSQL_HOST" -u "$MYSQL_USER" -p"$MYSQL_PASSWORD" "$DATABASE_NAME" < inventory_system.sql
  post_build:
    commands:
      # Additional post-build actions (e.g., restart services, clear caches)

artifacts:
  files: '**/*'
